default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: postgres
  database: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

production:
  url:      <%= ENV.fetch("DATABASE_URL") %>
  user:     <%= ENV.fetch("DATABASE_USER") %>
  database: <%= ENV.fetch("DATABASE_DATABASE") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 }     %>


