default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: postgres
  database: postgres
  password: postgres
  pool: <%= EnvVars["RAILS_MAX_THREADS"] %>

development:
  <<: *default

production:
  url:      <%= EnvVars["DATABASE_URL"     ] %>
  user:     <%= EnvVars["DATABASE_USER"    ] %>
  database: <%= EnvVars["DATABASE_DATABASE"] %>
  password: <%= EnvVars["DATABASE_PASSWORD"] %>
  pool:     <%= EnvVars["RAILS_MAX_THREADS"] %>


